### PR TITLE
Here comes typescript

### PR DESCRIPTION
**Pull request by javatlacati**
Please let me know what you think and keep the good work.

### CODE REVIEW

**Comment by tsreaper** [comment]
Wow. Typescript really makes Javascript more readable. Nice work.

I think it will be better to create a new branch for typescript so that people can choose the language they prefer, so I'll merge your pull request to that new branch.

**Comment by javatlacati** [comment]
awesome thank you, btw how do you think that we can integrate the activation function change in the dashboard?

**Comment by tsreaper** [comment]
I've updated the master branch. Users can now change the activation function in the dashboard. You can try it on the website (https://tsreaper.github.io/AI-Plays-FlappyBird/)

**Comment by javatlacati** [comment]
It's behaving weirdly can you check it again?

**Comment by tsreaper** [comment]
Do you mean the birds are not evolving well?

I've changed the input to the neural network a little. The height of the next-next-coming pipe is also fed to the neural network now (check README.md), so it'll be harder for the birds to evolve. But this new feature can help the birds fly better when the scrolling speed of the map becomes faster. Without this new feature, the birds might not be able to prepare themselves for a very sharp descend if the height of the next-next-coming pipe is low.

The hard point is that, when a bird evolves to aim at the next-next-coming pipe (instead of the next-coming pipe) at an early stage, as this bird may have a chance to fly through one pipe (if the height of the two coming pipes are similar) while other birds can't, this "wrong" gene will be quickly spread and it'll be harder for the later generations to correct this.

But from my experience, the birds under this new model will still evolve well after about 100~300 generations. It's just that they need a longer time as the model becomes more complicated.

**Comment by tsreaper** [comment]
I've added an option on the dashboard to let the user enable or disable this new feature (disabled by default).

**Pull request merged**
